#include "/Engine/Public/Platform.ush"

Texture2D ScreenTexture : register(T0);
SamplerState ScreenSampler : register(S0);

void MainVS(
	in float4 InPosition : ATTRIBUTE0,
	in float4 InUV: ATTRIBUTE1,
	out float2 OutUV : TEXCOORD0,
	out float4 OutPosition : SV_POSITION
)
{
	OutPosition = InPosition;
	OutUV = InUV;
}

void MainPS(
	in float4 UV : TEXCOORD0,
	out float4 OutColor1 : SV_Target0
)
{
	OutColor1 = ScreenTexture.Sample(ScreenSampler, UV.xy);
}